In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import os

In [65]:
df = pd.read_excel('../dataset/Telco_customer_churn.xlsx')

In [66]:
df.head()

,CustomerID,Count,Country,State,City,Zip Code,Lat Long,Latitude,Longitude,Gender,...,Contract,Paperless Billing,Payment Method,Monthly Charges,Total Charges,Churn Label,Churn Value,Churn Score,CLTV,Churn Reason
0,3668-QPYBK,1,United States,California,Los Angeles,90003,"33.964131, -118.272783",33.964131,-118.272783,Male,...,Month-to-month,Yes,Mailed check,53.85,108.15,Yes,1,86,3239,Competitor made better offer
1,9237-HQITU,1,United States,California,Los Angeles,90005,"34.059281, -118.30742",34.059281,-118.307420,Female,...,Month-to-month,Yes,Electronic check,70.70,151.65,Yes,1,67,2701,Moved
2,9305-CDSKC,1,United States,California,Los Angeles,90006,"34.048013, -118.293953",34.048013,-118.293953,Female,...,Month-to-month,Yes,Electronic check,99.65,820.5,Yes,1,86,5372,Moved
3,7892-POOKP,1,United States,California,Los Angeles,90010,"34.062125, -118.315709",34.062125,-118.315709,Female,...,Month-to-month,Yes,Electronic check,104.80,3046.05,Yes,1,84,5003,Moved
4,0280-XJGEX,1,United States,California,Los Angeles,90015,"34.039224, -118.266293",34.039224,-118.266293,Male,...,Month-to-month,Yes,Bank transfer (automatic),103.70,5036.3,Yes,1,89,5340,Competitor had better devices

In [67]:
df.columns

Index(['CustomerID', 'Count', 'Country', 'State', 'City', 'Zip Code',
       'Lat Long', 'Latitude', 'Longitude', 'Gender', 'Senior Citizen',
       'Partner', 'Dependents', 'Tenure Months', 'Phone Service',
       'Multiple Lines', 'Internet Service', 'Online Security',
       'Online Backup', 'Device Protection', 'Tech Support', 'Streaming TV',
       'Streaming Movies', 'Contract', 'Paperless Billing', 'Payment Method',
       'Monthly Charges', 'Total Charges', 'Churn Label', 'Churn Value',
       'Churn Score', 'CLTV', 'Churn Reason'],
      dtype='object')

In [68]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7043 entries, 0 to 7042
Data columns (total 33 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   CustomerID         7043 non-null   object
 1   Count              7043 non-null   int64
 2   Country            7043 non-null   object
 3   State              7043 non-null   object
 4   City               7043 non-null   object
 5   Zip Code           7043 non-null   int64
 6   Lat Long           7043 non-null   object
 7   Latitude           7043 non-null   float64
 8   Longitude          7043 non-null   float64
 9   Gender             7043 non-null   object
 10  Senior Citizen     7043 non-null   object
 11  Partner            7043 non-null   object
 12  Dependents         7043 non-null   object
 13  Tenure Months      7043 non-null   int64
 14  Phone Service      7043 non-null   object
 15  Multiple Lines     7043 non-null   object
 16  Internet Service   7043 non-null   object
 17  Online Security    7043 non-null   object
 18  Online Backup      7043 non-null   object
 19  Device Protection  7043 non-null   object
 20  Tech Support       7043 non-null   object
 21  Streaming TV       7043 non-null   object
 22  Streaming Movies   7043 non-null   object
 23  Contract           7043 non-null   object
 24  Paperless Billing  7043 non-null   object
 25  Payment Method     7043 non-null   object
 26  Monthly Charges    7043 non-null   float64
 27  Total Charges      7043 non-null   object
 28  Churn Label        7043 non-null   object
 29  Churn Value        7043 non-null   int64
 30  Churn Score        7043 non-null   int64
 31  CLTV               7043 non-null   int64
 32  Churn Reason       1869 non-null   object
dtypes: float64(3), int64(6), object(24)
memory usage: 1.8+ MB

--------Converting obj -> int/float-----------

----handling few columns manually with values yes and no we can also run a loop to find columns with values yes and no easily also it is given in kaggle which columns has yes and no values------

1. Handling Column Country

In [69]:
df['Country'].unique()

array(['United States'], dtype=object)

Since Country has only value - 'United States' i am removing it as it is not necessary

In [70]:
df.drop('Country', axis=1, inplace=True)

2. Handling States

In [71]:
df['State'].unique()

array(['California'], dtype=object)

Since State has only value - 'California' i am removing it as it is not necessary

In [72]:
df.drop('State', axis = 1, inplace=True)

3. Hnadling City

In [73]:
df['City'].unique()

array(['Los Angeles', 'Beverly Hills', 'Huntington Park', ..., 'Standish',
       'Tulelake', 'Olympic Valley'], shape=(1129,), dtype=object)

keeping city may be it has some other use as unique values > 1000

4. Gender

In [74]:
df['Gender'].unique()

array(['Male', 'Female'], dtype=object)

In [75]:
df['Gender'] = df['Gender'].map(lambda x: 1 if x=='Female' else 0)

In [76]:
df['Gender']

0       0
1       1
2       1
3       1
4       0
       ..
7038    1
7039    0
7040    1
7041    1
7042    0
Name: Gender, Length: 7043, dtype: int64

5. Senior Citizen

In [77]:
df['Senior Citizen'].unique()

array(['No', 'Yes'], dtype=object)

In [78]:
df['Senior Citizen'] = df['Senior Citizen'].map(lambda x: 1 if x=='Yes' else 0)

In [79]:
df['Senior Citizen']

0       0
1       0
2       0
3       0
4       0
       ..
7038    0
7039    0
7040    0
7041    0
7042    0
Name: Senior Citizen, Length: 7043, dtype: int64

In [80]:
df['Partner'].unique()

array(['No', 'Yes'], dtype=object)

########------one line solution for column with yes and no values--------

In [81]:
binary_cols = [col for col in df.columns if set(df[col].astype(str).str.strip().str.capitalize().dropna().unique()).issubset({'Yes','No'})]

In [82]:
binary_cols

['Partner', 'Dependents', 'Phone Service', 'Paperless Billing', 'Churn Label']

In [83]:
for col in binary_cols:
    df[col] = df[col].map(lambda x: 1 if x=='Yes' else 0)

In [84]:
df['Partner']

0       0
1       0
2       0
3       1
4       0
       ..
7038    0
7039    1
7040    1
7041    1
7042    0
Name: Partner, Length: 7043, dtype: int64

Now handling other columns

In [85]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7043 entries, 0 to 7042
Data columns (total 31 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   CustomerID         7043 non-null   object
 1   Count              7043 non-null   int64
 2   City               7043 non-null   object
 3   Zip Code           7043 non-null   int64
 4   Lat Long           7043 non-null   object
 5   Latitude           7043 non-null   float64
 6   Longitude          7043 non-null   float64
 7   Gender             7043 non-null   int64
 8   Senior Citizen     7043 non-null   int64
 9   Partner            7043 non-null   int64
 10  Dependents         7043 non-null   int64
 11  Tenure Months      7043 non-null   int64
 12  Phone Service      7043 non-null   int64
 13  Multiple Lines     7043 non-null   object
 14  Internet Service   7043 non-null   object
 15  Online Security    7043 non-null   object
 16  Online Backup      7043 non-null   object
 17  Device Protection  7043 non-null   object
 18  Tech Support       7043 non-null   object
 19  Streaming TV       7043 non-null   object
 20  Streaming Movies   7043 non-null   object
 21  Contract           7043 non-null   object
 22  Paperless Billing  7043 non-null   int64
 23  Payment Method     7043 non-null   object
 24  Monthly Charges    7043 non-null   float64
 25  Total Charges      7043 non-null   object
 26  Churn Label        7043 non-null   int64
 27  Churn Value        7043 non-null   int64
 28  Churn Score        7043 non-null   int64
 29  CLTV               7043 non-null   int64
 30  Churn Reason       1869 non-null   object
dtypes: float64(3), int64(13), object(15)
memory usage: 1.7+ MB

In [86]:
df['Multiple Lines'].unique()

array(['No', 'Yes', 'No phone service'], dtype=object)

In [87]:
df['Multiple Lines'] = df['Multiple Lines'].map(lambda x: 1 if x=='Yes' else 0)

In [88]:
df = pd.get_dummies(df, columns=['Internet Service'])

In [89]:
df['Online Security'].unique()

array(['Yes', 'No', 'No internet service'], dtype=object)

In [90]:
df['Online Security'] = df['Online Security'].map(lambda x: 1 if x=='Yes' else 0)

In [91]:
df['Online Backup'].unique()

array(['Yes', 'No', 'No internet service'], dtype=object)

In [92]:
df['Online Backup'] = df['Online Backup'].map(lambda x: 1 if x=='Yes' else 0)

In [93]:
df['Device Protection'].unique()

array(['No', 'Yes', 'No internet service'], dtype=object)

In [94]:
df['Device Protection'] = df['Device Protection'].map(lambda x: 1 if x=='Yes' else 0)

In [95]:
df['Tech Support'].unique()

array(['No', 'Yes', 'No internet service'], dtype=object)

In [96]:
df['Tech Support'] = df['Tech Support'].map(lambda x: 1 if x=='Yes' else 0)

In [97]:
df['Streaming TV'].unique()

array(['No', 'Yes', 'No internet service'], dtype=object)

In [98]:
df['Streaming TV'] = df['Streaming TV'].map(lambda x: 1 if x=='Yes' else 0)

In [99]:
df['Streaming Movies'].unique()

array(['No', 'Yes', 'No internet service'], dtype=object)

In [100]:
df['Streaming Movies'] = df['Streaming Movies'].map(lambda x: 1 if x=='Yes' else 0)

In [101]:
df['Contract'].unique()

array(['Month-to-month', 'Two year', 'One year'], dtype=object)

In [102]:
df['Contract'] = df['Contract'].map(lambda x: 1 if x=='Yes' else 0)

In [103]:
df['Payment Method'].unique()

array(['Mailed check', 'Electronic check', 'Bank transfer (automatic)',
       'Credit card (automatic)'], dtype=object)

In [104]:
df = pd.get_dummies(df,columns=['Payment Method'])

In [105]:
df['Total Charges'].unique()

array([108.15, 151.65, 820.5, ..., 7362.9, 346.45, 6844.5],
      shape=(6531,), dtype=object)

In [106]:
df['Total Charges'] = pd.to_numeric(df['Total Charges'],errors='coerce')

In [107]:
df['Total Charges'].unique()

array([ 108.15,  151.65,  820.5 , ..., 7362.9 ,  346.45, 6844.5 ],
      shape=(6531,))

In [108]:
reasons = df['Churn Reason'].unique()

In [109]:
reasons

array(['Competitor made better offer', 'Moved',
       'Competitor had better devices',
       'Competitor offered higher download speeds',
       'Competitor offered more data', 'Price too high',
       'Product dissatisfaction', 'Service dissatisfaction',
       'Lack of self-service on Website', 'Network reliability',
       'Limited range of services',
       'Lack of affordable download/upload speed',
       'Long distance charges', 'Extra data charges', "Don't know",
       'Poor expertise of online support',
       'Poor expertise of phone support', 'Attitude of service provider',
       'Attitude of support person', 'Deceased', nan], dtype=object)

In [110]:
missing_reason_df = df[(df['Churn Value']==1) & df['Churn Reason'].isna()]

In [111]:
missing_reason_df

Empty DataFrame
Columns: [CustomerID, Count, City, Zip Code, Lat Long, Latitude, Longitude, Gender, Senior Citizen, Partner, Dependents, Tenure Months, Phone Service, Multiple Lines, Online Security, Online Backup, Device Protection, Tech Support, Streaming TV, Streaming Movies, Contract, Paperless Billing, Monthly Charges, Total Charges, Churn Label, Churn Value, Churn Score, CLTV, Churn Reason, Internet Service_DSL, Internet Service_Fiber optic, Internet Service_No, Payment Method_Bank transfer (automatic), Payment Method_Credit card (automatic), Payment Method_Electronic check, Payment Method_Mailed check]
Index: []

[0 rows x 36 columns]

In [112]:
missing_reason_df2 = df[(df['Churn Value']==0) & (df['Churn Reason'].isna())]
missing_reason_df2

,CustomerID,Count,City,Zip Code,Lat Long,Latitude,Longitude,Gender,Senior Citizen,Partner,...,Churn Score,CLTV,Churn Reason,Internet Service_DSL,Internet Service_Fiber optic,Internet Service_No,Payment Method_Bank transfer (automatic),Payment Method_Credit card (automatic),Payment Method_Electronic check,Payment Method_Mailed check
1869,7590-VHVEG,1,Los Angeles,90001,"33.973616, -118.24902",33.973616,-118.249020,1,0,1,...,27,3964,NaN,True,False,False,False,False,True,False
1870,5575-GNVDE,1,Los Angeles,90002,"33.949255, -118.246978",33.949255,-118.246978,0,0,0,...,61,3441,NaN,True,False,False,False,False,False,True
1871,7795-CFOCW,1,Los Angeles,90004,"34.076259, -118.310715",34.076259,-118.310715,0,0,0,...,66,4307,NaN,True,False,False,True,False,False,False
1872,1452-KIOVK,1,Los Angeles,90007,"34.027337, -118.28515",34.027337,-118.285150,0,0,0,...,43,4459,NaN,False,True,False,False,True,False,False
1873,6713-OKOMC,1,Los Angeles,90008,"34.008293, -118.346766",34.008293,-118.346766,1,0,0,...,51,2013,NaN,True,False,False,False,False,False,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7038,2569-WGERO,1,Landers,92285,"34.341737, -116.539416",34.341737,-116.539416,1,0,0,...,45,5306,NaN,False,False,True,True,False,False,False
7039,6840-RESVB,1,Adelanto,92301,"34.667815, -117.536183",34.667815,-117.536183,0,0,1,...,59,2140,NaN,True,False,False,False,False,False,True
7040,2234-XADUH,1,Amboy,92304,"34.559882, -115.637164",34.559882,-115.637164,1,0,1,...,71,5560,NaN,False,True,False,False,True,False,False
7041,4801-JZAZL,1,Angelus Oaks,92305,"34.1678, -116.86433",34.167800,-116.864330,1,0,1,...,59,2793,NaN,True,False,False,False,False,True,False
7042,3186-AJIEK,1,Apple Valley,92308,"34.424926, -117.184503",34.424926,-117.184503,0,0,0,...,38,5097,NaN,False,True,False,True,False,False,False

In [113]:
def group_reasons(reason):
    if pd.isna(reason): return 'Active'
    reason = str(reason).lower()
    if 'competitor' in reason: return 'Competition'
    if 'price' in reason or 'charge' in reason: return 'Cost'
    if 'dissatisfaction' in reason or 'poor' in reason or 'reliability' in reason: return 'Service Quality'
    if 'moved' in reason or 'deceased' in reason: return 'Personal'
    return 'Other'
df['Churn Reason Grouped'] = df['Churn Reason'].apply(group_reasons)

In [114]:
missing_reason_df3 = df[(df['Churn Value']==0) & (df['Churn Reason'].isna()) & (df['Churn Reason Grouped'] != 'Active')]
missing_reason_df3

Empty DataFrame
Columns: [CustomerID, Count, City, Zip Code, Lat Long, Latitude, Longitude, Gender, Senior Citizen, Partner, Dependents, Tenure Months, Phone Service, Multiple Lines, Online Security, Online Backup, Device Protection, Tech Support, Streaming TV, Streaming Movies, Contract, Paperless Billing, Monthly Charges, Total Charges, Churn Label, Churn Value, Churn Score, CLTV, Churn Reason, Internet Service_DSL, Internet Service_Fiber optic, Internet Service_No, Payment Method_Bank transfer (automatic), Payment Method_Credit card (automatic), Payment Method_Electronic check, Payment Method_Mailed check, Churn Reason Grouped]
Index: []

[0 rows x 37 columns]

In [115]:
df = pd.get_dummies(df, columns=['Churn Reason Grouped'], prefix='Reason')

In [116]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7043 entries, 0 to 7042
Data columns (total 42 columns):
 #   Column                                    Non-Null Count  Dtype
---  ------                                    --------------  -----
 0   CustomerID                                7043 non-null   object
 1   Count                                     7043 non-null   int64
 2   City                                      7043 non-null   object
 3   Zip Code                                  7043 non-null   int64
 4   Lat Long                                  7043 non-null   object
 5   Latitude                                  7043 non-null   float64
 6   Longitude                                 7043 non-null   float64
 7   Gender                                    7043 non-null   int64
 8   Senior Citizen                            7043 non-null   int64
 9   Partner                                   7043 non-null   int64
 10  Dependents                                7043 non-null   int64
 11  Tenure Months                             7043 non-null   int64
 12  Phone Service                             7043 non-null   int64
 13  Multiple Lines                            7043 non-null   int64
 14  Online Security                           7043 non-null   int64
 15  Online Backup                             7043 non-null   int64
 16  Device Protection                         7043 non-null   int64
 17  Tech Support                              7043 non-null   int64
 18  Streaming TV                              7043 non-null   int64
 19  Streaming Movies                          7043 non-null   int64
 20  Contract                                  7043 non-null   int64
 21  Paperless Billing                         7043 non-null   int64
 22  Monthly Charges                           7043 non-null   float64
 23  Total Charges                             7032 non-null   float64
 24  Churn Label                               7043 non-null   int64
 25  Churn Value                               7043 non-null   int64
 26  Churn Score                               7043 non-null   int64
 27  CLTV                                      7043 non-null   int64
 28  Churn Reason                              1869 non-null   object
 29  Internet Service_DSL                      7043 non-null   bool
 30  Internet Service_Fiber optic              7043 non-null   bool
 31  Internet Service_No                       7043 non-null   bool
 32  Payment Method_Bank transfer (automatic)  7043 non-null   bool
 33  Payment Method_Credit card (automatic)    7043 non-null   bool
 34  Payment Method_Electronic check           7043 non-null   bool
 35  Payment Method_Mailed check               7043 non-null   bool
 36  Reason_Active                             7043 non-null   bool
 37  Reason_Competition                        7043 non-null   bool
 38  Reason_Cost                               7043 non-null   bool
 39  Reason_Other                              7043 non-null   bool
 40  Reason_Personal                           7043 non-null   bool
 41  Reason_Service Quality                    7043 non-null   bool
dtypes: bool(13), float64(4), int64(21), object(4)
memory usage: 1.6+ MB

In [117]:
df.drop('Churn Reason', axis = 1, inplace = True)

In [118]:
reason_cols = [col for col in df.columns if col.startswith('Reason_')]
df[reason_cols] = df[reason_cols].astype(int)

In [11]:
dfe = pd.read_excel('../dataset/Telco_customer_churn.xlsx')

In [ ]:
global_mean = df['Churn Value'].mean()

m = 10 

city_counts = df.groupby('City')['Churn Value'].count()
city_means = df.groupby('City')['Churn Value'].mean()

smoothed_city_map = (city_counts * city_means + m * global_mean) / (city_counts + m)

In [13]:
smoothed_city_map

City
Acampo          0.403836
Acton           0.189550
Adelanto        0.243580
Adin            0.332407
Agoura Hills    0.310247
                  ...
Yreka           0.189550
Yuba City       0.258539
Yucaipa         0.260978
Yucca Valley    0.176913
Zenia           0.260978
Name: Churn Value, Length: 1129, dtype: float64

In [121]:
df['City_Encoded'] = df['City'].map(smoothed_city_map)
df.drop('City', axis=1, inplace=True)

In [122]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7043 entries, 0 to 7042
Data columns (total 41 columns):
 #   Column                                    Non-Null Count  Dtype
---  ------                                    --------------  -----
 0   CustomerID                                7043 non-null   object
 1   Count                                     7043 non-null   int64
 2   Zip Code                                  7043 non-null   int64
 3   Lat Long                                  7043 non-null   object
 4   Latitude                                  7043 non-null   float64
 5   Longitude                                 7043 non-null   float64
 6   Gender                                    7043 non-null   int64
 7   Senior Citizen                            7043 non-null   int64
 8   Partner                                   7043 non-null   int64
 9   Dependents                                7043 non-null   int64
 10  Tenure Months                             7043 non-null   int64
 11  Phone Service                             7043 non-null   int64
 12  Multiple Lines                            7043 non-null   int64
 13  Online Security                           7043 non-null   int64
 14  Online Backup                             7043 non-null   int64
 15  Device Protection                         7043 non-null   int64
 16  Tech Support                              7043 non-null   int64
 17  Streaming TV                              7043 non-null   int64
 18  Streaming Movies                          7043 non-null   int64
 19  Contract                                  7043 non-null   int64
 20  Paperless Billing                         7043 non-null   int64
 21  Monthly Charges                           7043 non-null   float64
 22  Total Charges                             7032 non-null   float64
 23  Churn Label                               7043 non-null   int64
 24  Churn Value                               7043 non-null   int64
 25  Churn Score                               7043 non-null   int64
 26  CLTV                                      7043 non-null   int64
 27  Internet Service_DSL                      7043 non-null   bool
 28  Internet Service_Fiber optic              7043 non-null   bool
 29  Internet Service_No                       7043 non-null   bool
 30  Payment Method_Bank transfer (automatic)  7043 non-null   bool
 31  Payment Method_Credit card (automatic)    7043 non-null   bool
 32  Payment Method_Electronic check           7043 non-null   bool
 33  Payment Method_Mailed check               7043 non-null   bool
 34  Reason_Active                             7043 non-null   int64
 35  Reason_Competition                        7043 non-null   int64
 36  Reason_Cost                               7043 non-null   int64
 37  Reason_Other                              7043 non-null   int64
 38  Reason_Personal                           7043 non-null   int64
 39  Reason_Service Quality                    7043 non-null   int64
 40  City_Encoded                              7043 non-null   float64
dtypes: bool(7), float64(5), int64(27), object(2)
memory usage: 1.9+ MB

In [126]:
boo_cols = ['Internet Service_DSL','Internet Service_Fiber optic','Internet Service_No','Payment Method_Bank transfer (automatic)',
            'Payment Method_Credit card (automatic)','Payment Method_Electronic check','Payment Method_Mailed check']

df[boo_cols] = df[boo_cols].astype(int)

In [127]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7043 entries, 0 to 7042
Data columns (total 41 columns):
 #   Column                                    Non-Null Count  Dtype
---  ------                                    --------------  -----
 0   CustomerID                                7043 non-null   object
 1   Count                                     7043 non-null   int64
 2   Zip Code                                  7043 non-null   int64
 3   Lat Long                                  7043 non-null   object
 4   Latitude                                  7043 non-null   float64
 5   Longitude                                 7043 non-null   float64
 6   Gender                                    7043 non-null   int64
 7   Senior Citizen                            7043 non-null   int64
 8   Partner                                   7043 non-null   int64
 9   Dependents                                7043 non-null   int64
 10  Tenure Months                             7043 non-null   int64
 11  Phone Service                             7043 non-null   int64
 12  Multiple Lines                            7043 non-null   int64
 13  Online Security                           7043 non-null   int64
 14  Online Backup                             7043 non-null   int64
 15  Device Protection                         7043 non-null   int64
 16  Tech Support                              7043 non-null   int64
 17  Streaming TV                              7043 non-null   int64
 18  Streaming Movies                          7043 non-null   int64
 19  Contract                                  7043 non-null   int64
 20  Paperless Billing                         7043 non-null   int64
 21  Monthly Charges                           7043 non-null   float64
 22  Total Charges                             7032 non-null   float64
 23  Churn Label                               7043 non-null   int64
 24  Churn Value                               7043 non-null   int64
 25  Churn Score                               7043 non-null   int64
 26  CLTV                                      7043 non-null   int64
 27  Internet Service_DSL                      7043 non-null   int64
 28  Internet Service_Fiber optic              7043 non-null   int64
 29  Internet Service_No                       7043 non-null   int64
 30  Payment Method_Bank transfer (automatic)  7043 non-null   int64
 31  Payment Method_Credit card (automatic)    7043 non-null   int64
 32  Payment Method_Electronic check           7043 non-null   int64
 33  Payment Method_Mailed check               7043 non-null   int64
 34  Reason_Active                             7043 non-null   int64
 35  Reason_Competition                        7043 non-null   int64
 36  Reason_Cost                               7043 non-null   int64
 37  Reason_Other                              7043 non-null   int64
 38  Reason_Personal                           7043 non-null   int64
 39  Reason_Service Quality                    7043 non-null   int64
 40  City_Encoded                              7043 non-null   float64
dtypes: float64(5), int64(34), object(2)
memory usage: 2.2+ MB

In [128]:
df.drop('Lat Long', axis=1, inplace=True)

In [129]:
from sklearn.cluster import DBSCAN
coords = np.radians(df[['Latitude', 'Longitude']])
db = DBSCAN(eps = 0.001, min_samples=10, metric='haversine')
df['Cluster_Labels'] = db.fit_predict(coords)

In [130]:
df.head()

,CustomerID,Count,Zip Code,Latitude,Longitude,Gender,Senior Citizen,Partner,Dependents,Tenure Months,...,Payment Method_Electronic check,Payment Method_Mailed check,Reason_Active,Reason_Competition,Reason_Cost,Reason_Other,Reason_Personal,Reason_Service Quality,City_Encoded,Cluster_Labels
0,3668-QPYBK,1,90003,33.964131,-118.272783,0,0,0,0,2,...,0,1,0,1,0,0,0,0,0.294139,0
1,9237-HQITU,1,90005,34.059281,-118.307420,1,0,0,1,2,...,1,0,0,0,0,0,1,0,0.294139,0
2,9305-CDSKC,1,90006,34.048013,-118.293953,1,0,0,1,8,...,1,0,0,0,0,0,1,0,0.294139,0
3,7892-POOKP,1,90010,34.062125,-118.315709,1,0,1,1,28,...,1,0,0,0,0,0,1,0,0.294139,0
4,0280-XJGEX,1,90015,34.039224,-118.266293,0,0,0,1,49,...,0,0,0,1,0,0,0,0,0.294139,0

In [131]:
df[(df['Tenure Months']==0) & (df['Total Charges'].isna())]

,CustomerID,Count,Zip Code,Latitude,Longitude,Gender,Senior Citizen,Partner,Dependents,Tenure Months,...,Payment Method_Electronic check,Payment Method_Mailed check,Reason_Active,Reason_Competition,Reason_Cost,Reason_Other,Reason_Personal,Reason_Service Quality,City_Encoded,Cluster_Labels
2234,4472-LVYGI,1,92408,34.084909,-117.258107,1,0,1,0,0,...,0,0,1,0,0,0,0,0,0.280360,0
2438,3115-CZMZD,1,93526,36.869584,-118.189241,0,0,0,0,0,...,0,1,1,0,0,0,0,0,0.260978,-1
2568,5709-LVOEQ,1,94401,37.590421,-122.306467,1,0,1,0,0,...,0,1,1,0,0,0,0,0,0.294373,10
2667,4367-NUYAO,1,95014,37.306612,-122.080621,0,0,1,1,0,...,0,1,1,0,0,0,0,0,0.332407,10
2856,1371-DWPAZ,1,95569,40.363446,-123.835041,1,0,1,0,0,...,0,0,1,0,0,0,0,0,0.189550,-1
4331,7644-OMVMY,1,90029,34.089953,-118.294824,0,0,1,1,0,...,0,1,1,0,0,0,0,0,0.294139,0
4687,3213-VVOLG,1,92585,33.739412,-117.173334,0,0,1,1,0,...,0,1,1,0,0,0,0,0,0.256986,6
5104,2520-SGTTA,1,95005,37.078873,-122.090386,1,0,1,1,0,...,0,1,1,0,0,0,0,0,0.260978,24
5719,2923-ARZLG,1,91750,34.144703,-117.770299,0,0,1,1,0,...,0,1,1,0,0,0,0,0,0.176913,0
6772,4075-WKNIU,1,90201,33.970343,-118.171368,1,0,1,1,0,...,0,1,1,0,0,0,0,0,0.176913,0
6840,2775-SEFEE,1,90744,33.782068,-118.262263,0,0,0,1,0,...,0,0,1,0,0,0,0,0,0.176913,0

In [132]:
df['Total Charges'] = df['Total Charges'].fillna(0)

In [133]:
df['Tenure_Pee_Dollar'] = df['Tenure Months']/(df['Monthly Charges']+1)

In [134]:
df['Avg_Historical_Monthly'] = df['Total Charges'] / (df['Tenure Months'] + 1)

In [135]:
df['Price_Hike_Indicator'] = df['Monthly Charges'] / (df['Avg_Historical_Monthly'] + 1)

In [136]:
service_cols = [
    'Phone Service', 'Multiple Lines', 'Online Security', 
    'Online Backup', 'Device Protection', 'Tech Support', 
    'Streaming TV', 'Streaming Movies'
]

df['Total_Services'] = df[service_cols].sum(axis=1)

df['Cost_Per_Service'] = np.where(
    df['Total_Services'] > 0, 
    df['Monthly Charges'] / df['Total_Services'], 
    df['Monthly Charges']
)

In [137]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7043 entries, 0 to 7042
Data columns (total 46 columns):
 #   Column                                    Non-Null Count  Dtype
---  ------                                    --------------  -----
 0   CustomerID                                7043 non-null   object
 1   Count                                     7043 non-null   int64
 2   Zip Code                                  7043 non-null   int64
 3   Latitude                                  7043 non-null   float64
 4   Longitude                                 7043 non-null   float64
 5   Gender                                    7043 non-null   int64
 6   Senior Citizen                            7043 non-null   int64
 7   Partner                                   7043 non-null   int64
 8   Dependents                                7043 non-null   int64
 9   Tenure Months                             7043 non-null   int64
 10  Phone Service                             7043 non-null   int64
 11  Multiple Lines                            7043 non-null   int64
 12  Online Security                           7043 non-null   int64
 13  Online Backup                             7043 non-null   int64
 14  Device Protection                         7043 non-null   int64
 15  Tech Support                              7043 non-null   int64
 16  Streaming TV                              7043 non-null   int64
 17  Streaming Movies                          7043 non-null   int64
 18  Contract                                  7043 non-null   int64
 19  Paperless Billing                         7043 non-null   int64
 20  Monthly Charges                           7043 non-null   float64
 21  Total Charges                             7043 non-null   float64
 22  Churn Label                               7043 non-null   int64
 23  Churn Value                               7043 non-null   int64
 24  Churn Score                               7043 non-null   int64
 25  CLTV                                      7043 non-null   int64
 26  Internet Service_DSL                      7043 non-null   int64
 27  Internet Service_Fiber optic              7043 non-null   int64
 28  Internet Service_No                       7043 non-null   int64
 29  Payment Method_Bank transfer (automatic)  7043 non-null   int64
 30  Payment Method_Credit card (automatic)    7043 non-null   int64
 31  Payment Method_Electronic check           7043 non-null   int64
 32  Payment Method_Mailed check               7043 non-null   int64
 33  Reason_Active                             7043 non-null   int64
 34  Reason_Competition                        7043 non-null   int64
 35  Reason_Cost                               7043 non-null   int64
 36  Reason_Other                              7043 non-null   int64
 37  Reason_Personal                           7043 non-null   int64
 38  Reason_Service Quality                    7043 non-null   int64
 39  City_Encoded                              7043 non-null   float64
 40  Cluster_Labels                            7043 non-null   int64
 41  Tenure_Pee_Dollar                         7043 non-null   float64
 42  Avg_Historical_Monthly                    7043 non-null   float64
 43  Price_Hike_Indicator                      7043 non-null   float64
 44  Total_Services                            7043 non-null   int64
 45  Cost_Per_Service                          7043 non-null   float64
dtypes: float64(9), int64(36), object(1)
memory usage: 2.5+ MB

In [138]:
df['Count'].unique()

array([1])

In [3]:
from sklearn.model_selection import train_test_split, RepeatedStratifiedKFold, cross_val_score
from sklearn.preprocessing import StandardScaler, OneHotEncoder
from sklearn.compose import ColumnTransformer
from sklearn.pipeline import Pipeline
from imblearn.over_sampling import SMOTE
from imblearn.pipeline import Pipeline as ImbPipeline
from sklearn.ensemble import RandomForestClassifier, StackingClassifier
from xgboost import XGBClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.calibration import CalibratedClassifierCV
from sklearn.metrics import classification_report, roc_auc_score

In [5]:
leakage_cols = [
    'Churn Label', 
    'Churn Score', 
    'CLTV', 
    'CustomerID', 
    'Count', 
    'Zip Code'
]
reason_cols = [col for col in df.columns if 'Reason_' in col]

X = df.drop(columns=leakage_cols + reason_cols + ['Churn Value', 'Lat Long'], errors='ignore')
y = df['Churn Value']

In [6]:

base_models = [
    ('xgb', XGBClassifier(n_estimators=200, max_depth=4, learning_rate=0.05, scale_pos_weight=3, random_state=42)),
    ('rf', RandomForestClassifier(n_estimators=200, max_depth=12, class_weight='balanced', random_state=42))
]

stacker = StackingClassifier(
    estimators=base_models,
    final_estimator=LogisticRegression(),
    cv=5
)

model_pipeline = ImbPipeline(steps=[
    ('scaler', StandardScaler()),
    ('smote', SMOTE(random_state=42)),
    ('stacking', stacker)
])

In [7]:
final_model = CalibratedClassifierCV(model_pipeline, cv=3,method='sigmoid')

X_train, X_test, y_train, y_test = train_test_split(X,y,test_size=0.2, stratify=y, random_state=42)
final_model.fit(X_train, y_train)

CalibratedClassifierCV(cv=3,
                       estimator=Pipeline(steps=[('scaler', StandardScaler()),
                                                 ('smote',
                                                  SMOTE(random_state=42)),
                                                 ('stacking',
                                                  StackingClassifier(cv=5,
                                                                     estimators=[('xgb',
                                                                                  XGBClassifier(base_score=None,
                                                                                                booster=None,
                                                                                                callbacks=None,
                                                                                                colsample_bylevel=None,
                                                                                                colsample_bynode=None,
                                                                                                colsample_bytree=None,
                                                                                                device=None,
                                                                                                early_stopping_rounds=None,
                                                                                                enable_categoric...
                                                                                                max_cat_to_onehot=None,
                                                                                                max_delta_step=None,
                                                                                                max_depth=4,
                                                                                                max_leaves=None,
                                                                                                min_child_weight=None,
                                                                                                missing=nan,
                                                                                                monotone_constraints=None,
                                                                                                multi_strategy=None,
                                                                                                n_estimators=200,
                                                                                                n_jobs=None,
                                                                                                num_parallel_tree=None, ...)),
                                                                                 ('rf',
                                                                                  RandomForestClassifier(class_weight='balanced',
                                                                                                         max_depth=12,
                                                                                                         n_estimators=200,
                                                                                                         random_state=42))],
                                                                     final_estimator=LogisticRegression()))]))

In [8]:
probs = final_model.predict_proba(X_test)[:,1]
preds = final_model.predict(X_test)

print(classification_report(y_test, preds))
print(f"ULTIMATE ROC-AUC: {roc_auc_score(y_test, probs):.4f}")

              precision    recall  f1-score   support

           0       0.88      0.90      0.89      1035
           1       0.71      0.67      0.69       374

    accuracy                           0.84      1409
   macro avg       0.80      0.78      0.79      1409
weighted avg       0.84      0.84      0.84      1409

ULTIMATE ROC-AUC: 0.8963

In [152]:
import joblib
model_features = X.columns.tolist()
joblib.dump(model_features, 'model_features.pkl')

['model_features.pkl']

In [ ]:
joblib.dump(final_model, 'trained_model.pkl')

['trained_model.pkl']

In [17]:
joblib.dump(smoothed_city_map.to_dict(),'../churn-app/model/city_map.pkl')

['../churn-app/model/city_map.pkl']